# Special Functions & Matrix Operations

In [2]:
import numpy as np
import pandas as pd
from bokeh.plotting import figure, output_notebook, show
from bokeh.models import Range1d
from scipy import stats

In [6]:
output_notebook()

Loading BokehJS ...

In [13]:
sgmd = lambda x: 1 / (1 + np.exp(-x))

In [14]:
x = np.linspace(-2*np.pi, 2*np.pi, 100)
y1 = np.exp(x)
y2 = sgmd(x)
p2 = figure(plot_width=400, plot_height=400)
p2.multi_line([x,x,x],[y1,-y1,y2],
            color=["firebrick", "navy","orange"], alpha=[0.8, 0.3, .5], line_width=4)
show(p2)

In [24]:
x = np.linspace(-2*np.pi,2*np.pi, 100)
p3 = figure(plot_width=400, plot_height=400)
p3.line(x,sgmd(x),line_width=2, legend='y = 1/(1+exp(-x))')
p3.legend.location = 'bottom_right'
show(p3)

In [22]:
x = np.linspace(-1, 1, 100)
y1 = x
y2 = x**2
y3 = x**3
y4 = x**4
y5 = x**5
powers = figure(plot_width=400, plot_height=400)
powers.line(x,y1,color='firebrick',alpha=.5,line_width=2,legend='y=x')
powers.line(x,y2,color='navy',alpha=.5,line_width=2,legend='y=x^2')
powers.line(x,y3,color='orange',alpha=.5,line_width=2,legend='y=x^3')
powers.line(x,y4,color='blue',alpha=.5,line_width=2,legend='y=x^4')
powers.line(x,y5,color='green',alpha=.5,line_width=2,legend='y=x^5')
powers.legend.location = 'bottom_right'
show(powers)

In [31]:

x = np.linspace(-2, 2, 100)
yn2 = np.exp(-2*x)
yn1 = np.exp(-x)
y1 = np.exp(x)
y2 = np.exp(2*x)
powers = figure(plot_width=400, plot_height=400)
powers.line(x,yn2,color='red',alpha=.5,line_width=2,legend='y=exp(-2x)')
powers.line(x,yn1,color='orange',alpha=.5,line_width=2,legend='y=exp(-x)')
powers.line(x,y1,color='green',alpha=.5,line_width=2,legend='y=exp(x)')
powers.line(x,y2,color='blue',alpha=.5,line_width=2,legend='y=exp(2x)')
powers.legend.location = 'center'
show(powers)

In [37]:
x = np.linspace(-np.pi, np.pi, 100)
y1 = np.sin(x)
y2 = np.cos(x)
powers = figure(plot_width=400, plot_height=400)
powers.line(x,y1,color='red',alpha=.5,line_width=2,legend='y=sin(x)')
powers.line(x,y2,color='orange',alpha=.5,line_width=2,legend='y=cos(x)')
powers.legend.location = 'top_left'
show(powers)

In [41]:
x = np.linspace(-5, 5, 100)
y = stats.norm.pdf(x)
powers = figure(plot_width=400, plot_height=400)
powers.line(x,y,color='red',alpha=.5,line_width=2,legend='The Gaussian')
powers.legend.location = 'top_left'
show(powers)

In [50]:
x = np.linspace(-5, 5, 100)
y = stats.norm.pdf(x)
y1 = stats.norm.cdf(x)
powers = figure(plot_width=400, plot_height=400)
powers.line(x,y,color='red',alpha=.5,line_width=2,legend='The Gaussian (density)')
powers.line(x,y1,color='blue',alpha=.5,line_width=2,legend='TheGassian (cdf)')
powers.legend.location = 'top_left'
show(powers)

In [43]:
pcws = lambda x: 0 if x < 0 else x
pcws(-5)

0

In [45]:
x = np.linspace(-1, 1, 100)
y = [pcws(a) for a in x]
powers = figure(plot_width=400, plot_height=400)
powers.line(x,y,color='red',alpha=.5,line_width=2,legend='Rectifier')
powers.legend.location = 'top_left'
show(powers)

## Matrix Operations

In [47]:
# Defining a matrix A
A = np.array([[1,1,0],[0,1,1],[0,0,2]])
# Computing its eigenstuff
w,v = np.linalg.eig(A)

In [48]:
# The eigenvalues of A
w

array([ 1.,  1.,  2.])

In [49]:
# Some eigenvectors of A
v

array([[  1.00000000e+00,  -1.00000000e+00,   5.77350269e-01],
       [  0.00000000e+00,   2.22044605e-16,   5.77350269e-01],
       [  0.00000000e+00,   0.00000000e+00,   5.77350269e-01]])

### Multiplying Matrices

In [60]:
# Let's check that that worked...
np.matmul(A-np.identity(3),v)

array([[  0.00000000e+00,   2.22044605e-16,   5.77350269e-01],
       [  0.00000000e+00,   0.00000000e+00,   5.77350269e-01],
       [  0.00000000e+00,   0.00000000e+00,   5.77350269e-01]])

In [59]:
np.matmul(A-2*np.identity(3),v)

array([[ -1.00000000e+00,   1.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,  -2.22044605e-16,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

### Matrices as Functions

In [7]:
# Let's plot this figure
p = figure(plot_width=400, plot_height=400)
x = [1, 2, 3, 4, 5]
y = [6, 7, 8, 7, 3]
# add a patch renderer with an alpha an line width
p.patch(x, y, alpha=0.5, line_width=2)
show(p)

In [8]:
# Let's define a matrix and see what it does
M = np.array([[2,0],[0,1]])
output = np.matmul(M,np.array([x,y]))

In [9]:
# Finally, we'll update the figure and plot again.
x = output[0,:]
y = output[1,:]
# add a patch renderer with an alpha an line width
f = figure(plot_width=400, plot_height=400)
f.patch(x, y, alpha=0.5, line_width=2)
show(f)

In [ ]:
# Let's define another matrix and see what it does
A = np.array([[np.cos(np.pi/4),-np.sin(np.pi/4)],[np.sin(np.pi/4),np.cos(np.pi/4)]])

# Now let's feed it to our matrix multiplication function.
output = np.matmul(A,np.array([x,y]))

In [87]:
# Finally, we'll update the figure and plot again.
x = output[0,:]
y = output[1,:]
# add a patch renderer with an alpha an line width
q = figure(plot_width=400, plot_height=400)
q.patch(x, y, alpha=0.5, line_width=2)
show(q)